from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

# the DefaultRouter is a feature of the Djando rest_framework
# that will automatically generate the URLs for our viewset
# when have viewset may have mutiple URLs associated with
# one viewset /api/recipe/tags/{}
# creates a new object router
routers = DefaultRouter()
# this register our viewset with out router
routers.register('tags', views.TagViewSet)
routers.register('ingredients', views.IngredientViewSet)

app_name = 'recipe'

urlpatterns = [
    # all the URLs that are generated by our default router
    # then will be include in the URL patterns
    # and if we add any more viewset they automatically
    # have all of the URLs generated
    path('', include(routers.urls))
]
